export interface MovieModel {
    id: string,
    title: string,
    saleavailable: boolean,
    rentavailable: boolean,
    commingsoon: boolean,
    saleprice: number,
    rentalprice: number,
    year: number,
    runtime: number,
    plot: string,   
    rated: string,
    released: string,
    genre: string,
    director: string,
    writer: string,
    actors: string,
    language:  string,
    country: string,
    awards: string,
    cardimg: string,
    posterimg: string,
    bannerimg: string,
    urltrailer: string  
}
