export interface MovieModel {
    id: string,
    title: string,
    year: number,
    saleprice: number,
    rentalprice: number,
    canbesold: string,
    canberent: string,
    commingsoon: string,
    noavailable: string,
    rated: string,
    released: string,
    runtime: number,
    genre: string,
    director: string,
    writer: string,
    actors: string,
    plot: string,
    language:  string,
    country: string,
    awards: string,
    cardimg: string,
    posterimg: string,
    bannerimg: string,
    urltrailer: string  
}
